### ISSUE TITLE
Install on virtual machine

### ISSUE THREAD

**Issue by unforgivablesin** [systemd/particleos#17]
I tried to install ParticleOS on a virtual machine. It doesn't appear to be working. I made 2 Virtio disks. 1 disk with the particleOS base raw image that gets created from:

```bash
mkosi -d fedora -t disk -f
```

And one qcow2 created disk. I boot the virtual machine and it starts, however I get:

```bash
[FAILED] Failed to start systemd-repart.service - Repartition Root Disk.
````

Is there any resource on how to set it up for it to work?

**Comment by MoltenArmor** [comment]
The information you provide is not enough to position the problem.

After `systemd-repart.service` failed, systemd typically enters `emergency.target` and executes `sulogin`. But according to my experience, you might not be able to use it because the root user is locked.

If you encounter this issue, add `SYSTEMD_SULOGIN_FORCE=1` to the kernel command line and try to boot the system again. This should allow you to enter the emergency shell when `systemd-repart.service` fails. After that, please provide the output of `systemctl status systemd-repart.service` for further diagnosis.

**Comment by unforgivablesin** [comment]
Ah I see the issue at hand. I built it with `-t disk` and it gave me a .raw file, the disk itself is 1.8G and it says it needs 17.7G space. 

"Can't fit requested partitions into available free space (0B)."

Now im still not sure how to get it as a VM image correctly.

**Comment by unforgivablesin** [comment]
Thank you! However I do not want to run QEMU from mkosi and rather from virt manager. Are the steps still the same for this? Thanks again!

**Comment by unforgivablesin** [comment]
I do not use `mkosi -f qemu` the exact command I used to build the image is in the ticket.

**Comment by unforgivablesin** [comment]
Thanks a lot. The steps provided solved my issue!
